// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.TodoApp = (function(superClass) {
    extend(TodoApp, superClass);

    function TodoApp() {
      this.index = bind(this.index, this);
      this.initialize = bind(this.initialize, this);
      return TodoApp.__super__.constructor.apply(this, arguments);
    }

    TodoApp.prototype.initialize = function() {
      this.todoItems = new TodoItems();
      this.todosView = new TodosView({
        collection: this.todoItems
      });
      this.todosView.render();
      $('.btn-clear').click((function(_this) {
        return function(e) {
          return _this.todosView.filterCompleted();
        };
      })(this));
      return $('.btn-success').click((function(_this) {
        return function(e) {
          _this.todoItems.create({
            val: $('#newTodo').val(),
            completed: false
          });
          return $('#newTodo').val('');
        };
      })(this));
    };

    TodoApp.prototype.routes = {
      '': 'index'
    };

    TodoApp.prototype.index = function() {
      $('#app').html(this.todosView.el);
      return this.todoItems.fetch();
    };

    TodoApp.prototype.start = function() {
      return Backbone.history.start();
    };

    return TodoApp;

  })(Backbone.Router);

}).call(this);

//# sourceMappingURL=router.js.map
